### ISSUE TITLE
Licensed Scrum Masterの資格名称変更

### ISSUE THREAD

**Issue by yu-koito** [onestop-techbook/Agile2#7]
＞Scrum Inc. が提供する認定スクラムマスター(Licensed Scrum Master)
去年くらいに「Registered Scrum Master」に名前変わったので、修正いただけるとありがたいですー
https://scruminc.jp/training/master/

グループ会社なのでとりあえず指摘

＞2022 年4 月時点で、日本では、Scrum Inc. Japan のみが研修を提供をしています。
最近だと、永和さんがやったりしてます。が、直すかどうかはお任せします。
https://www.agile-studio.jp/post/agile-angya

**Comment by scrummasudar** [comment]
@yu-koito 
起票ありがとうございます。

ただ、mainブランチにマージ済みの原稿では、既に両方とも対応済みです。
https://github.com/onestop-techbook/Agile2/blob/main/articles/chap-scrummasudar.re

どのブランチでご確認されましたでしょうか？

**Comment by yu-koito** [comment]
ローカルの古い版見てました
失礼しました
